apiVersion: apps/v1
kind: Deployment
metadata:
  name: homework-deploy
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: homework
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: homework
    spec:
      containers:
      - name: homework
        image: antfere/homework:latest
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: homework-svc
  labels:
    app: homework
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30080
    protocol: TCP
  selector:
    app: homework

